# Generated by Django 3.0.1 on 2022-11-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link debajo para Post', max_length=255),
        ),
    ]
